# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kamil/Dokumenty/gissupport/projekty/wtyczki/uldk/wyszukiwarka-gugik-uldk/wyszukiwarka-gugik-uldk/modules/csv_import/main_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(468, 698)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.import_csv_file_select = gui.QgsFileWidget(self.frame_2)
        self.import_csv_file_select.setObjectName("import_csv_file_select")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.import_csv_file_select)
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_info_import_csv_column = QtWidgets.QLabel(self.frame_2)
        self.label_info_import_csv_column.setMaximumSize(QtCore.QSize(15, 15))
        self.label_info_import_csv_column.setScaledContents(True)
        self.label_info_import_csv_column.setObjectName("label_info_import_csv_column")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_info_import_csv_column)
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.formLayout_4)
        self.import_csv_combobox_teryt_column = QtWidgets.QComboBox(self.frame_2)
        self.import_csv_combobox_teryt_column.setCurrentText("")
        self.import_csv_combobox_teryt_column.setObjectName("import_csv_combobox_teryt_column")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.import_csv_combobox_teryt_column)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.import_csv_layer_name = QtWidgets.QLineEdit(self.frame_2)
        self.import_csv_layer_name.setObjectName("import_csv_layer_name")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.import_csv_layer_name)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_5.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_info_import_csv = QtWidgets.QLabel(self.frame_2)
        self.label_info_import_csv.setMaximumSize(QtCore.QSize(15, 15))
        self.label_info_import_csv.setScaledContents(True)
        self.label_info_import_csv.setObjectName("label_info_import_csv")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_info_import_csv)
        self.import_csv_start = QtWidgets.QPushButton(self.frame_2)
        self.import_csv_start.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_csv_start.sizePolicy().hasHeightForWidth())
        self.import_csv_start.setSizePolicy(sizePolicy)
        self.import_csv_start.setMinimumSize(QtCore.QSize(50, 0))
        self.import_csv_start.setObjectName("import_csv_start")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.import_csv_start)
        self.formLayout_5.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.formLayout_6)
        self.verticalLayout.addWidget(self.frame_2)
        self.import_csv_cancel = QtWidgets.QPushButton(Frame)
        self.import_csv_cancel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_csv_cancel.sizePolicy().hasHeightForWidth())
        self.import_csv_cancel.setSizePolicy(sizePolicy)
        self.import_csv_cancel.setObjectName("import_csv_cancel")
        self.verticalLayout.addWidget(self.import_csv_cancel)
        self.import_csv_progress = QtWidgets.QProgressBar(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_csv_progress.sizePolicy().hasHeightForWidth())
        self.import_csv_progress.setSizePolicy(sizePolicy)
        self.import_csv_progress.setMinimumSize(QtCore.QSize(350, 0))
        self.import_csv_progress.setProperty("value", 0)
        self.import_csv_progress.setObjectName("import_csv_progress")
        self.verticalLayout.addWidget(self.import_csv_progress)
        self.import_csv_label_status = QtWidgets.QLabel(Frame)
        self.import_csv_label_status.setObjectName("import_csv_label_status")
        self.verticalLayout.addWidget(self.import_csv_label_status)
        self.import_csv_label_found_count = QtWidgets.QLabel(Frame)
        self.import_csv_label_found_count.setIndent(6)
        self.import_csv_label_found_count.setObjectName("import_csv_label_found_count")
        self.verticalLayout.addWidget(self.import_csv_label_found_count)
        self.import_csv_label_not_found_count = QtWidgets.QLabel(Frame)
        self.import_csv_label_not_found_count.setIndent(6)
        self.import_csv_label_not_found_count.setObjectName("import_csv_label_not_found_count")
        self.verticalLayout.addWidget(self.import_csv_label_not_found_count)
        self.import_csv_table_errors = QtWidgets.QTableWidget(Frame)
        self.import_csv_table_errors.setObjectName("import_csv_table_errors")
        self.import_csv_table_errors.setColumnCount(0)
        self.import_csv_table_errors.setRowCount(0)
        self.verticalLayout.addWidget(self.import_csv_table_errors)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Plik"))
        self.import_csv_file_select.setFilter(_translate("Frame", "*.csv"))
        self.label_2.setText(_translate("Frame", "Kolumna TERYT"))
        self.label_info_import_csv_column.setToolTip(_translate("Frame", "Możesz ręcznie wpisać kod TERYT działki"))
        self.label_info_import_csv_column.setText(_translate("Frame", "i"))
        self.label_3.setText(_translate("Frame", "Nazwa nowej\n"
"warstwy"))
        self.import_csv_layer_name.setPlaceholderText(_translate("Frame", "nowa_warstwa"))
        self.label_info_import_csv.setToolTip(_translate("Frame", "Możesz ręcznie wpisać kod TERYT działki"))
        self.label_info_import_csv.setText(_translate("Frame", "i"))
        self.import_csv_start.setText(_translate("Frame", "Start"))
        self.import_csv_cancel.setText(_translate("Frame", "Anuluj"))
        self.import_csv_label_status.setText(_translate("Frame", "TextLabel"))
        self.import_csv_label_found_count.setText(_translate("Frame", "TextLabel"))
        self.import_csv_label_not_found_count.setText(_translate("Frame", "TextLabel"))

from qgis import gui
