# -*- coding: utf-8 -*-
"""
/***************************************************************************
 wyszukiwarkaDzialekDockWidget
                                 A QGIS plugin
 desc
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-05
        git sha              : $Format:%H$
        copyright            : (C) 2018 by umcs
        email                : mail@mail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import random

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.core import QgsMapLayerProxyModel
from qgis.gui import QgsMapLayerComboBox
from qgis.utils import iface

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'plugin_dockwidget_base.ui'))

def usemaps_ads_generator():
    """Generator haseł marketingowych Usemaps"""
    ads_pool = [
        ("Twoje dane w QGIS widzisz tylko Ty.&nbsp;Usemaps to zmienia.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Dowiedz się więcej"),
        ("QGIS dla Ciebie.&nbsp;Usemaps dla całego Zespołu.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy dla całej organizacji"),
        ("Pracujesz na plikach.&nbsp;Zespół potrzebuje wiedzy.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Poznaj Usemaps"),
        ("Jeden projekt,&nbsp;wiele wersji?&nbsp;Usemaps wprowadza porządek.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy całej organizacji"),
        ("Projekty OZE wymagają współpracy.&nbsp;Usemaps ją umożliwia.", "https://usemaps.com/usemaps-renewables/?utm_source=qgis_plugin","Poznaj Usemaps dla OZE"),
        ("Od plików do platformy.&nbsp;Usemaps zmienia sposób pracy z GIS.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Dowiedz się więcej"),
        ("Inwestycje OZE nie lubią zwłoki.&nbsp;Usemaps przyspiesza obieg informacji.", "https://usemaps.com/usemaps-renewables/?utm_source=qgis_plugin","Poznaj Usemaps dla OZE"),
        ("Zapomnij o wersji „final_v2”.&nbsp;Z Usemaps masz zawsze aktualne dane.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy całej organizacji"),
        ("Ty masz dane w QGIS.&nbsp;Reszta zespołu ma tylko pytania.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz rozwiązanie"),
        ("Mapy dla inwestycji.&nbsp;Dane dla całego zespołu w Usemaps.", "https://usemaps.com/usemaps-renewables/?utm_source=qgis_plugin","Poznaj Usemaps dla OZE"),
        ("Robisz analizy.&nbsp;Zespół robi screeny.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Odkryj Usemaps"),
        ("Lokalizacja idealna.&nbsp;Szkoda,&nbsp;że tylko w Twoim QGIS.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy całej organizacji"),
        ("Działki sprawdzone.&nbsp;Każda w innym pliku.", "https://usemaps.com/usemaps-renewables/?utm_source=qgis_plugin","Poznaj Usemaps dla OZE"),
        ("Światłowód w terenie.&nbsp;Dane gdzieś w mailu.", "https://usemaps.com/usemaps-network/?utm_source=qgis_plugin","Zobacz jak zbierać dane w jednym miejscu"),
        ("Dane o sieci są.&nbsp;Tylko trzeba je znaleźć.", "https://usemaps.com/usemaps-network/?utm_source=qgis_plugin","W Usemaps wszystko widzisz."),
        ("Decyzje za miliony.&nbsp;Dane w załączniku.zip.", "https://usemaps.com/usemaps-renewables/?utm_source=qgis_plugin","Poznaj Usemaps dla OZE"),
        ("Mapy robisz świetne.&nbsp;Szkoda,&nbsp;że tylko Ty je widzisz.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy całej organizacji"),
        ("„Masz aktualne dane?”&nbsp;Najczęściej zadawane pytanie w GIS", "https://usemaps.com/usemaps-renewables/?utm_source=qgis_plugin","Dowiedz się, jak to zmienić"),
        ("Dane gotowe.&nbsp;Synchronizacja…&nbsp;kiedyś.&nbsp;Usemaps ją umożliwia.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy całej organizacji"),
        ("Każda obserwacja ma znaczenie.&nbsp;Pod warunkiem,&nbsp;że ktoś ją widzi.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Dowiedz się więcej"),
        ("Twoje mapy są świetne.&nbsp;Z Usemaps wreszcie zobaczy je cały zespół.", "https://usemaps.com/usemaps-qgis/?utm_source=qgis_plugin","Zobacz jak udostępnić mapy całej organizacji")
    ]
    while True:
        random.shuffle(ads_pool)
        for ad in ads_pool:
            yield ad

class wyszukiwarkaDzialekDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(wyszukiwarkaDzialekDockWidget, self).__init__(parent)
        self.setupUi(self)

        self.ad_generator = usemaps_ads_generator()
        self._build_save_menu()

        pages_gen = self._generate_page(5)

        self.page_search, self.tab_teryt_search_layout = next(pages_gen)
        self.page_csv, self.tab_import_csv_layout = next(pages_gen)
        self.page_from_csv, self.tab_from_csv_file_layout = next(pages_gen)
        self.page_layer, self.tab_import_layer_layout = next(pages_gen)
        self.page_check, self.tab_check_layer_layout = next(pages_gen)

        self.pages = [
            self.page_search,
            self.page_csv,
            self.page_from_csv,
            self.page_layer,
            self.page_check
        ]

        # Logika otwierania przyciskami
        self.btn_tab_search.clicked.connect(lambda: self._switch_tool(0))
        self.btn_tab_search.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_teryt.svg'))
        self.btn_tab_search.setToolTip(("Pojedynczo"))

        self.btn_tab_import_csv.clicked.connect(lambda: self._switch_tool(1))
        self.btn_tab_import_csv.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_from_list.svg'))
        self.btn_tab_import_csv.setToolTip(("Z listy"))

        self.btn_tab_from_csv_file.clicked.connect(lambda: self._switch_tool(2))
        self.btn_tab_from_csv_file.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_from_csv.svg'))
        self.btn_tab_from_csv_file.setToolTip(("Z pliku CSV"))

        self.btn_tab_import_layer.clicked.connect(lambda: self._switch_tool(3))
        self.btn_tab_import_layer.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_from_layer.svg'))
        self.btn_tab_import_layer.setToolTip(("Z warstwy"))

        self.btn_tab_check_layer.clicked.connect(lambda: self._switch_tool(4))
        self.btn_tab_check_layer.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_check_layer.svg'))
        self.btn_tab_check_layer.setToolTip(("Sprawdź"))

        self.btn_save_settings.setToolTip(("Ustawienia zapisu"))
        self.btn_save_settings.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_settings.svg'))

        self.btn_info.clicked.connect(self._show_info_dialog)
        self.btn_info.setIcon(QIcon(':/plugins/gissupport_plugin/uldk/uldk_plugin_info.svg'))
        self.btn_info.setToolTip(("O wtyczce"))

        self._apply_theme_style()

        # Załadowanie pierwszej zakładki
        self.btn_tab_search.setChecked(True)
        self._switch_tool(0)

    def _generate_page(self, count: int):
        """Generator tworzący kontenery (QWidget) oraz przypięte do nich layouty"""
        for _ in range(count):
            page = QtWidgets.QWidget()
            layout = QtWidgets.QVBoxLayout(page)
            layout.setContentsMargins(0, 0, 0, 0)
            yield page, layout

    def _switch_tool(self, index: int) -> None:
        target_layout = self.scrollAreaWidgetContents.layout()

        while target_layout.count():
            item = target_layout.takeAt(0)
            if item.widget():
                item.widget().setParent(None)

        target_layout.addWidget(self.pages[index], alignment=Qt.AlignmentFlag.AlignTop)

        # Logika widoczności menu zapisu przy zakładce Sprawdź
        if index == 4:
            self.radioTempLayer.setChecked(True)
            self.radioExistingLayer.setEnabled(False)
            self.comboLayers.setEnabled(False)
        else:
            self.radioExistingLayer.setEnabled(True)
            self.comboLayers.setEnabled(self.radioExistingLayer.isChecked())

    def _build_save_menu(self) -> None:
        self._save_menu = QtWidgets.QMenu(self)
        container = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(container)
        layout.setContentsMargins(8, 6, 8, 8)
        layout.setSpacing(6)

        self.radioTempLayer = QtWidgets.QRadioButton(
            "Zapisz w warstwie tymczasowej", container
        )
        self.radioTempLayer.setChecked(True)
        layout.addWidget(self.radioTempLayer)

        row = QtWidgets.QHBoxLayout()
        row.setSpacing(4)
        row.setContentsMargins(0, 0, 0, 0)

        self.radioExistingLayer = QtWidgets.QRadioButton(
            "Dodaj do istniejącej warstwy", container
        )
        row.addWidget(self.radioExistingLayer)

        self.comboLayers = QgsMapLayerComboBox(container)
        self.comboLayers.setFilters(QgsMapLayerProxyModel.Filter.PolygonLayer)
        self.comboLayers.setEnabled(False)
        self.comboLayers.setMinimumWidth(130)
        row.addWidget(self.comboLayers)

        self.labelLayerInfo = QtWidgets.QLabel(container)
        self.labelLayerInfo.setMaximumSize(15, 15)
        self.labelLayerInfo.setScaledContents(True)
        self.labelLayerInfo.setToolTip(
            "Atrybuty będą dopasowane do kolumn wg nazw, jeśli dana kolumna nie istnieje "
            "to informacja nie zostanie zapisana:\n"
            "- wojewodztwo lub woj - województwo\n"
            "- powiat - powiat\n"
            "- gmina - gmina\n"
            "- obreb - obręb ewidencyjny\n"
            "- arkusz - arkusz mapy\n"
            "- nr_dzialki - numer działki\n"
            "- teryt - TERYT\n"
            "- pow_m2 - powierzchnia"
        )
        row.addWidget(self.labelLayerInfo)

        layout.addLayout(row)

        self.radioExistingLayer.toggled.connect(self.comboLayers.setEnabled)

        widget_action = QtWidgets.QWidgetAction(self._save_menu)
        widget_action.setDefaultWidget(container)
        self._save_menu.addAction(widget_action)

        self.btn_save_settings.setMenu(self._save_menu)
        self.btn_save_settings.setPopupMode(
            QtWidgets.QToolButton.ToolButtonPopupMode.InstantPopup
        )

    def _apply_theme_style(self) -> None:
        qgis_font = iface.layerTreeView().font()
        font_family = qgis_font.family()
        font_size = qgis_font.pointSize()
        
        if font_size > 0:
            font_css = f"font-size: {font_size}pt;"
        else:
            font_css = f"font-size: {qgis_font.pixelSize()}px;"

        self.setStyleSheet(f"""
            QWidget {{
                font-family: "{font_family}";
                {font_css}
            }}
            QScrollArea#scrollArea {{
                background-color: palette(base);
                margin-top: 4px;
            }}
            QWidget#scrollAreaWidgetContents {{
                background-color: transparent;
            }}
        """)


        if self.palette().color(QtGui.QPalette.ColorRole.Window).lightness() < 128:
            self.scrollArea.setStyleSheet(self.scrollArea.styleSheet() + """
                QLineEdit{
                    background-color: #383838;
                    border: 2px solid #383838;
                    border-radius: 2px;
                }

                QTableWidget, QProgressBar, QDoubleSpinBox, QgsCheckableComboBox{
                    background-color: #383838;
                }

                QPushButton, QComboBox {
                    color: #eeeeee;
                }
            """)

    def showEvent(self, event):
        super(wyszukiwarkaDzialekDockWidget, self).showEvent(event)
        self._setup_usemaps_banner()

    def _setup_usemaps_banner(self) -> None:
        """Konfiguruje banner"""

        ad = next(self.ad_generator)
        self.label_usemaps_text.setTextFormat(Qt.TextFormat.RichText)
        self.label_usemaps_text.setText(
            f'<html><body><p align="center">{ad[0]}</p></body></html>'
        )
        self.label_usemaps_link.setText(
            f'<html><body><p align="center" style="font-size:10pt;">'
            f'<a href="{ad[1]}"><span style="text-decoration: underline; color:#0000ff;">'
            f'{ad[2]}</span></a></p></body></html>'
        )

    def _show_info_dialog(self) -> None:
        """Wyświetla okno z info o wtyczce"""

        uic.loadUi(
            os.path.join(os.path.dirname(__file__), 'info_dialog.ui'),
            QtWidgets.QDialog(self)
        ).exec()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
