# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kamil/Dokumenty/gissupport/projekty/wtyczki/uldk/wyszukiwarka-gugik-uldk/wyszukiwarka-gugik-uldk/modules/teryt_search/main_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(429, 703)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_province = QtWidgets.QLabel(Frame)
        self.label_province.setObjectName("label_province")
        self.verticalLayout.addWidget(self.label_province)
        self.combobox_province = QtWidgets.QComboBox(Frame)
        self.combobox_province.setObjectName("combobox_province")
        self.verticalLayout.addWidget(self.combobox_province)
        self.label_county = QtWidgets.QLabel(Frame)
        self.label_county.setObjectName("label_county")
        self.verticalLayout.addWidget(self.label_county)
        self.combobox_county = QtWidgets.QComboBox(Frame)
        self.combobox_county.setObjectName("combobox_county")
        self.verticalLayout.addWidget(self.combobox_county)
        self.label_municipality = QtWidgets.QLabel(Frame)
        self.label_municipality.setObjectName("label_municipality")
        self.verticalLayout.addWidget(self.label_municipality)
        self.combobox_municipality = QtWidgets.QComboBox(Frame)
        self.combobox_municipality.setObjectName("combobox_municipality")
        self.verticalLayout.addWidget(self.combobox_municipality)
        self.label_precinct = QtWidgets.QLabel(Frame)
        self.label_precinct.setObjectName("label_precinct")
        self.verticalLayout.addWidget(self.label_precinct)
        self.combobox_precinct = QtWidgets.QComboBox(Frame)
        self.combobox_precinct.setObjectName("combobox_precinct")
        self.verticalLayout.addWidget(self.combobox_precinct)
        self.label_teryt = QtWidgets.QLabel(Frame)
        self.label_teryt.setObjectName("label_teryt")
        self.verticalLayout.addWidget(self.label_teryt)
        self.lineedit_plot_id = QtWidgets.QLineEdit(Frame)
        self.lineedit_plot_id.setEnabled(True)
        self.lineedit_plot_id.setMinimumSize(QtCore.QSize(150, 0))
        self.lineedit_plot_id.setReadOnly(False)
        self.lineedit_plot_id.setClearButtonEnabled(False)
        self.lineedit_plot_id.setObjectName("lineedit_plot_id")
        self.verticalLayout.addWidget(self.lineedit_plot_id)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_full_id = QtWidgets.QLabel(Frame)
        self.label_full_id.setObjectName("label_full_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_full_id)
        self.label_info_full_id = QtWidgets.QLabel(Frame)
        self.label_info_full_id.setMaximumSize(QtCore.QSize(15, 15))
        self.label_info_full_id.setScaledContents(True)
        self.label_info_full_id.setObjectName("label_info_full_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_info_full_id)
        self.verticalLayout.addLayout(self.formLayout)
        self.lineedit_full_teryt = QtWidgets.QLineEdit(Frame)
        self.lineedit_full_teryt.setEnabled(True)
        self.lineedit_full_teryt.setMinimumSize(QtCore.QSize(150, 0))
        self.lineedit_full_teryt.setReadOnly(False)
        self.lineedit_full_teryt.setClearButtonEnabled(False)
        self.lineedit_full_teryt.setObjectName("lineedit_full_teryt")
        self.verticalLayout.addWidget(self.lineedit_full_teryt)
        spacerItem = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.button_search = QtWidgets.QPushButton(Frame)
        self.button_search.setEnabled(False)
        self.button_search.setObjectName("button_search")
        self.verticalLayout.addWidget(self.button_search)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_sheet = QtWidgets.QLabel(Frame)
        self.label_sheet.setObjectName("label_sheet")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sheet)
        self.label_info_sheet = QtWidgets.QLabel(Frame)
        self.label_info_sheet.setMaximumSize(QtCore.QSize(15, 15))
        self.label_info_sheet.setScaledContents(True)
        self.label_info_sheet.setObjectName("label_info_sheet")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_info_sheet)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.combobox_sheet = QtWidgets.QComboBox(Frame)
        self.combobox_sheet.setEnabled(False)
        self.combobox_sheet.setObjectName("combobox_sheet")
        self.verticalLayout.addWidget(self.combobox_sheet)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_province.setText(_translate("Frame", "Województwo:"))
        self.label_county.setText(_translate("Frame", "Powiat:"))
        self.label_municipality.setText(_translate("Frame", "Gmina:"))
        self.label_precinct.setText(_translate("Frame", "Obręb:"))
        self.label_teryt.setText(_translate("Frame", "Numer działki:"))
        self.label_full_id.setText(_translate("Frame", "Pełny numer działki (opcjonalny)"))
        self.label_info_full_id.setToolTip(_translate("Frame", "Możesz ręcznie wpisać kod TERYT działki"))
        self.label_info_full_id.setText(_translate("Frame", "i"))
        self.button_search.setText(_translate("Frame", "Szukaj"))
        self.label_sheet.setText(_translate("Frame", "Arkusz:"))
        self.label_info_sheet.setToolTip(_translate("Frame", "Możesz ręcznie wpisać kod TERYT działki"))
        self.label_info_sheet.setText(_translate("Frame", "i"))

